window.VIXTA_COLLECTION = {
  version: 1,
  featuredBook: "point-noir-intersystemique",
  books: [
    {
      id: "point-noir-intersystemique",
      slug: "le-point-noir-intersystemique",
      title: "Le Point Noir Intersystémique",
      subtitle: "Les configurations du dialogue",
      shortTitle: "Intersystémique",
      href: "#edition",
      purchaseUrl: "https://www.amazon.fr/dp/B0GT5YD9NK",
      excerptUrl: "extrait-le-point-noir-intersystemique.pdf",
      published: true,
      front: "assets/couverture-le-point-noir-intersystemique.png",
      back: "assets/couverture-dos.webp",
      spine: "assets/couverture-tranche.webp",
      render: "assets/v3/photo-principale-livre.svg",
      renderWidth: 1152,
      renderHeight: 1536,
      frontWidth: 1624,
      frontHeight: 2500,
      spineWidth: 120,
      soundProfile: [392, 493.88, 587.33],
    },
  ],
};
